/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Johan
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    int esAdmin;
    
    public Administracion(int esAdmin) {
        initComponents();
          this.esAdmin= esAdmin;//para poder recibir esto, tuve que eliminar el setVisible que
          //estaba en el metodo main de esta clase, de otra forma no me dejaba recibirlo
        btnRegistroProducto.setVisible(false);
        btnRegistroEmpleado.setVisible(false);
        
        System.out.println(esAdmin+"aqui");
        if(esAdmin==1){
            btnRegistroProducto.setVisible(true);
            btnRegistroEmpleado.setVisible(true);
        }
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistroProducto = new javax.swing.JButton();
        btnRegistroCliente = new javax.swing.JButton();
        btnCatalogo = new javax.swing.JButton();
        btnRegistroEmpleado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistroProducto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegistroProducto.setText("Registro de Producto");
        btnRegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroProductoActionPerformed(evt);
            }
        });

        btnRegistroCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegistroCliente.setText("Registro de cliente");
        btnRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroClienteActionPerformed(evt);
            }
        });

        btnCatalogo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCatalogo.setText("Catálogo");
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });

        btnRegistroEmpleado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegistroEmpleado.setText("Registro de Empleado");
        btnRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Rinconcito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistroProducto)
                    .addComponent(btnCatalogo))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistroCliente)
                    .addComponent(btnRegistroEmpleado))
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatalogo)
                    .addComponent(btnRegistroCliente))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroProducto)
                    .addComponent(btnRegistroEmpleado))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroProductoActionPerformed
        // TODO add your handling code here:
        frmProducto formProducto= new frmProducto();
        formProducto.setLocationRelativeTo(null);
        formProducto.setVisible(true);
    }//GEN-LAST:event_btnRegistroProductoActionPerformed

    private void btnRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroClienteActionPerformed
        // TODO add your handling code here:
        frmCliente formCliente= new frmCliente();
        formCliente.setLocationRelativeTo(null);
        formCliente.setVisible(true);
    }//GEN-LAST:event_btnRegistroClienteActionPerformed

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        // TODO add your handling code here:
        Catalogo entrarCatalago= new Catalogo();
        entrarCatalago.setLocationRelativeTo(null);
        entrarCatalago.setVisible(true);
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEmpleadoActionPerformed
        // TODO add your handling code here:
        frmEmpleado formEmpleado= new frmEmpleado();
        formEmpleado.setLocationRelativeTo(null);
        formEmpleado.setVisible(true);
    }//GEN-LAST:event_btnRegistroEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnRegistroCliente;
    private javax.swing.JButton btnRegistroEmpleado;
    private javax.swing.JButton btnRegistroProducto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
